version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocyclo
    - godox
    - mnd
    - goprintffuncname
    - govet
    - intrange
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

  settings:
    dupl:
      threshold: 100

    funlen:
      lines: -1
      statements: 50

    goconst:
      min-len: 2
      min-occurrences: 3

    gocyclo:
      min-complexity: 15

    godox:
      keywords:
        - FIXME
        - TODO
        - NOTE
        - BUG

    mnd:
      checks:
        - argument
        - case
        - condition
        - return
      ignored-numbers:
        - '0'
        - '1'
        - '2'
        - '3'
      ignored-functions:
        - strings.SplitN

    govet:
      enable:
        - nilness
        - shadow

    errorlint:
      asserts: false

    lll:
      line-length: 120

    misspell:
      locale: US

    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: true

    revive:
      rules:
        - name: indent-error-flow
        - name: unexported-return
          disabled: true
        - name: unused-parameter
        - name: unused-receiver

issues:
  exclude-rules:
    # Исключаем проверки для тестов
    - path: (.+)_test\.go
      linters:
        - dupl
        - mnd
        - lll
        - funlen
        - gocyclo
        - noctx

    # Исключаем проверки для миграций
    - path: migrations
      linters:
        - all

    # Исключаем проверки для cmd/migrate
    - path: cmd/migrate
      linters:
        - errcheck
        - revive
        - unused

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'

    goimports:
      local-prefixes:
        - github.com/Bobb1n/Reminder_Hub
